### ISSUE TITLE
Can't Compile When Signing

### ISSUE THREAD

**Issue by Cimplex** [Fody/ExtraConstraints#5]
I get an error when I try to compile this with a pfx file:

'''
Error   2   Fody: An unhandled exception occurred:

Exception:
Unable to obtain public key for StrongNameKeyPair.

StackTrace:
   at System.Reflection.StrongNameKeyPair.ComputePublicKey()
   at System.Reflection.StrongNameKeyPair.get_PublicKey()
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters) in c:\Code\cecil\Mono.Cecil\AssemblyWriter.cs:line 100
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters) in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 933
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters) in c:\Code\cecil\Mono.Cecil\ModuleDefinition.cs:line 922
   at InnerWeaver.WriteModule() in c:\Code\Fody\FodyIsolated\ModuleWriter.cs:line 20
   at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 34

Source:
mscorlib

TargetSite:
Byte[] ComputePublicKey()
    ExtraConstraints
'''

I've never got an exception dump in the error list before so I don't really know where to go from here.

**Comment by BennyBread** [comment]
Hi, I just stumbled upon this. I had indeed the same problem. One of my assemblies had a password protected key. 
Removing the password solved the problem. 
Maybee it would be a relly good idea to change the error message to display that circumstance.

**Comment by SimonCropp** [comment]
@BennyBread sounds good. Feel free to send a pull request that improves the error message

**Comment by Janek91** [comment]
It may be a stupid question, but why assemblies with password protected keys cannot be supported?

**Comment by SimonCropp** [comment]
@BennyBread 

> Maybee it would be a relly good idea to change the error message to display that circumstance.

sounds good. please submit a PR

**Comment by SimonCropp** [comment]
@Janek91 because that information is not exposed through msbuild. and also since SN is not about security https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx

> Do not rely on strong names for security. 

So going to extra effort to password protect something that is not a security feature seems pointless

**Comment by artemious7** [comment]
Same just happened to me. Error message is useless.

**Comment by SimonCropp** [comment]
@artemious7 feel free to submit a PR that improves the error message
